# Global pipeline settings
pipeline:
  input_dir: "data/raw"
  output_dir: "data/outputs"
  tile_size: 1024
  overlap_ratio: 0.3
  min_text_height: 6
  max_text_height: 100
  device: "cuda:0"  # or "cpu"
  debug: True
  debug_visualization: True

data_loader:
  sahi_slicer_output_dir: "data/outputs/data_loader/slice"
  metadata_output_dir: "data/outputs/data_loader/metadata"
