# Global pipeline settings
pipeline:
  input_dir: "data/raw"
  output_dir: "data/outputs"
  tile_size: 1024
  overlap_ratio: 0.5
  min_text_height: 6
  max_text_height: 100
  device: "cuda:0"  # or "cpu"
  debug: True
  debug_visualization: True

data_loader:
  sahi_slicer_output_dir: "data/processed/tiles"
  metadata_output_dir: "data/processed/metadata"
  tile_metadata_dir : "data/processed/metadata/tile_metadata"
  group_detection_metadata_dir : "data/processed/metadata/group_detection_metadata"
  global_metadata_dir : "data/processed/metadata/global_metadata"
  detection_metadata_dir : "data/processed/metadata/detection_metadata"
  core_tile_metadata_dir : "data/processed/metadata/core_tile_metadata"
  core_detection_metadata_dir : "data/processed/metadata/core_detection_metadata"

# in configs/base.yaml
# A good starting point. Increase if you have more VRAM.
  # ... other ocr settings from run_pipeline.py if you want them here