# Global pipeline settings
pipeline:
  input_dir: "data/raw"
  output_dir: "data/outputs"
  min_text_height: 6
  max_text_height: 100
  device: "cuda:0"  # or "cpu"
  debug: True
  debug_visualization: True

# --- NEW: SAHI Slicer Configuration ---
sahi_slicer:
  tile_size: 1050
  overlap_ratio: 0.5
  min_area_ratio: 0.1
  verbose: False

data_loader:
  sahi_slicer_output_dir: "data/processed/tiles"
  metadata_output_dir: "data/processed/metadata"
  tile_metadata_dir : "data/processed/metadata/tile_metadata"
  group_detection_metadata_dir : "data/processed/metadata/group_detection_metadata"
  global_metadata_dir : "data/processed/metadata/global_metadata"
  detection_metadata_dir : "data/processed/metadata/detection_metadata"
  core_tile_metadata_dir : "data/processed/metadata/core_tile_metadata"
  core_detection_metadata_dir : "data/processed/metadata/core_detection_metadata"

# --- OCR Configuration ---
ocr:
  languages: ['en']
  gpu: True
  confidence_threshold: 0.3
  rotation_angles: [0, 90]
  filter_overlaps: True
  # iou_threshold: 0.5 # IoU threshold for filtering overlapping boxes from different rotations
