# configs/cropping.yaml

cropping:
  # Padding in pixels to add around the bounding box of the detected text.
  padding: 10

  # The minimum confidence score of a grouped text line required to be cropped.
  # Value should be between 0.0 and 1.0.
  min_confidence: 0.4

  # The directory where the original images are stored.
  # This should match the pipeline's input_dir.
  image_source_dir: "data/raw"

  # The directory containing the JSON files with grouped text detections.
  grouped_text_dir: "data/processed/metadata/final_grouped_text"

  # The base directory to save the cropped image folders.
  output_dir: "data/processed/cropping"