# configs/grouping.yaml

# --- Grouping Parameters (No changes) ---
grouping:
  h_height_tolerance: 0.3
  h_proximity_factor: 0.75
  h_min_vertical_overlap: 0.1
  v_width_tolerance: 0.3
  v_proximity_factor: 0.75
  v_min_horizontal_overlap: 0.1

# --- 1. Pre-Grouping Filters (Applied before grouping) ---
pre_group_filtering:
  # Basic quality filters
  min_confidence: 0.3
  min_area: 10  # Min bbox area in pixels to be considered

  # Soft-NMS Filter (now applied before grouping)
  soft_nms:
    enabled: true
    iou_threshold: 0.5
    sigma: 0.5
    min_confidence: 0.3 # Min confidence to keep a box after suppression

# --- 2. Post-Grouping Filters (Applied after grouping) ---
post_group_filtering:
  # P&ID-specific aspect ratio filtering
  smart_aspect_ratio:
    enabled: true
    # Adaptive thresholds based on text length: max_ratio = base_ratio + (text_length * length_factor)
    base_ratio: 0.3
    length_factor: 0.02