# Existing parameters
height_tolerance: 0.2
width_tolerance: 0.2
proximity_factor: 2.5
confidence_threshold: 0.3
max_dimension_expansion: 1.5

# New irregular box filtering parameters
filter_irregular_boxes: true
horizontal_aspect_ratio_threshold: 1  # For 0° text: width/height >= 0.5
vertical_aspect_ratio_threshold: 1     # For 90° text: height/width >= 2.0

# Project paths
tile_metadata_dir: "data/processed/metadata/tile_metadata"
detection_metadata_dir: "data/processed/metadata/detection_metadata"
output_dir: "data/processed/metadata/group_detection_metadata"