# OCR settings
ocr:
  model_type: "parseq"  # "master" alternative
  model_path: "models/ocr/parseq.pth"
  input_size: [32, 128]
  preprocessing:
    deskew: True
    contrast_enhancement: "adaptive_histogram"
    normalize_illumination: True
  postprocessing:
    character_set: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-()" 
    dictionary_path: "data/pid_dictionary.txt"