# Configuration for the Re-OCR step on cropped images.
re_ocr:
  # Input directory where the cropped image folders are located.
  # This should match the output directory of the 'crop' step.
  input_dir: "data/processed/cropping"

  # Directory to save the final JSON annotation files.
  output_dir: "data/processed/metadata/final_annotations"

  # OCR settings for the second pass (on cropped images).
  # No rotation is needed as crops are already oriented horizontally.
  languages: ['en']
  gpu: True

  # A confidence threshold for the re-recognized text to be included in the final output.
  min_confidence: 0.1